# Generated by Django 2.0.3 on 2018-05-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeoffTime', models.DateTimeField()),
                ('landingTime', models.DateTimeField()),
                ('landingAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='flights.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('passengerLimit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketCount', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Passenger')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('name', 'surname')},
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Plane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='takeoffAirport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='flights.Airport'),
        ),
    ]
