# Generated by Django 2.0.3 on 2018-05-13 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='passengerLimit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('passenger', 'flight')},
        ),
    ]
