# Generated by Django 2.0.3 on 2018-06-07 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_reservation_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cptName', models.TextField()),
                ('cptSurname', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticketCount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('cptName', 'cptSurname')},
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Crew'),
        ),
    ]
